In [6]:
import numpy as np
from numpy import linalg as LA
from scipy.sparse.linalg import eigsh
from scipy.linalg import eig
import plotly.graph_objects as go

### For schrodinger 

$-(1+i\alpha)\frac{\hbar^2}{2m}\frac{\partial^2{\psi}}{\partial{x}^2}+\frac{1}{2}m\omega^2x^2\psi = E\psi$

In [7]:
# constant define

N_points = 1000

k = 1
m = 1
h_bar = 1
alpha = 1e-4

omega = np.sqrt(k/m)

width = 5
up_bound = width
dn_bound = -width

# slice grid

del_s = (up_bound - dn_bound)/(N_points - 1)

x_grid = np.linspace(dn_bound,up_bound,N_points,dtype=float)

# system define 

def potential (x_grid):
    return 0.5 * m * omega**2 * x_grid**2




In [8]:
D_0 = np.diag(-2*np.ones(N_points),k=0)
D_1 = np.diag(np.ones(N_points-1),k=1)
D_2 = np.diag(np.ones(N_points-1),k=-1)


D = (D_0 + D_1 + D_2)


T_hat = -(1+alpha*1j) * h_bar**2 * D /(2 * m * del_s**2)

V_hat = np.diag(potential(x_grid),k=0)

H_hat = T_hat + V_hat

E , psi = LA.eigh(H_hat)
psi = np.array(psi)


In [9]:

# Normalization
for i in range(6):
    psi[:,i] = psi[:,i]/np.sqrt(np.linalg.norm(psi[:,i]**2))


In [10]:
#plot the wave function from the eigen function

fig = go.Figure()
for i in range(6):
    fig.add_trace(go.Scatter(x=x_grid,y = np.real(psi[:,i]), name=f"psi_{i}"))


fig.update_layout(
    title="Wave function (REAL part)",
    xaxis_title="sptial_x",
    yaxis_title="psi",
    legend_title="Legend",
    font=dict(
        size=18,
    )
)

fig.update_layout(margin=dict(l=20, r=200, t=20, b=20),)
fig.add_annotation(dict(font=dict(color='yellow',size=15),
    x=1.02, y=0.2, showarrow=False,
    text = f'ℏ = {h_bar}<br>α = {alpha}<br>m = {m}<br>k = {k}<br>ω = {omega}',
    textangle=0, xanchor='left', xref="paper", yref="paper"))

fig.update_layout(template='plotly_dark',showlegend=True)
fig.write_html("Non_hermition_REAL.html")
fig.show()

In [11]:
#plot the wave function from the eigen function

fig = go.Figure()
for i in range(6):
    fig.add_trace(go.Scatter(x=x_grid,y = np.imag(psi[:,i]), name=f"psi_{i}"))


fig.update_layout(
    title="Wave function (IMAG part)",
    xaxis_title="sptial_x",
    yaxis_title="psi",
    legend_title="Legend",
    font=dict(
        size=18,
    )
)
fig.update_layout(margin=dict(l=20, r=200, t=20, b=20))

fig.update_layout(template='plotly_dark',showlegend=True)
fig.write_html("Non_hermition_IMAG.html")
fig.show()

In [12]:
E

array([4.99946970e-01, 1.49993445e+00, 2.49990948e+00, 3.49987295e+00,
       4.49983339e+00, 5.49985070e+00, 6.50024597e+00, 7.50234498e+00,
       8.51033718e+00, 9.53419136e+00, 1.05914474e+01, 1.17046770e+01,
       1.28951541e+01, 1.41777512e+01, 1.55602790e+01, 1.70457080e+01,
       1.86345611e+01, 2.03263960e+01, 2.21205028e+01, 2.40161759e+01,
       2.60127992e+01, 2.81098593e+01, 3.03069353e+01, 3.26036826e+01,
       3.49998178e+01, 3.74951057e+01, 4.00893493e+01, 4.27823812e+01,
       4.55740577e+01, 4.84642540e+01, 5.14528600e+01, 5.45397776e+01,
       5.77249182e+01, 6.10082011e+01, 6.43895515e+01, 6.78688998e+01,
       7.14461801e+01, 7.51213300e+01, 7.88942897e+01, 8.27650011e+01,
       8.67334080e+01, 9.07994553e+01, 9.49630888e+01, 9.92242550e+01,
       1.03582901e+02, 1.08038973e+02, 1.12592420e+02, 1.17243187e+02,
       1.21991223e+02, 1.26836474e+02, 1.31778887e+02, 1.36818407e+02,
       1.41954981e+02, 1.47188554e+02, 1.52519069e+02, 1.57946472e+02,
      

In [87]:
a = [i for i in range(9)]
a.append(1+5j)
a = np.diag(np.array(a),k = 0)
a[0][7] = 1+5j

eig(a)

(array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
        8.+0.j, 1.+5.j]),
 array([[1.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.11547005+0.57735027j,
         0.        +0.j        , 0.        +0.j        ],
        [0.        +0.j        , 1.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ],
        [0.        +0.j        , 0.        +0.j        ,
         1.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ,
         0.        +0.j        , 0.        +0.j        ],
        [0.        +0.j        , 0.        +

In [94]:
# convert the matrix to MATLAB format
for i in range(10):
    output = [f'{j.real} + {j.imag}i' for j in a[i]]
    print(" ".join(output),end = ';')

0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 1.0 + 5.0i 0.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i 1.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i 0.0 + 0.0i 2.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 3.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 4.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 5.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 6.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 7.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 0.0 + 0.0i 8.0 + 0.0i 0.0 + 0.0i;0.0 + 0.0i

In [141]:
N_matrix = 10
D_0 = np.array([[(1+alpha*1j/2)*(n+1/2) if m==n else 0 for n in range(N_matrix)] for m in range(N_matrix)])
D_1 = np.array([[-(h_bar*omega*alpha*1j)/4*np.sqrt(n+1) * np.sqrt(n+2) if m==n+2 else 0 for n in range(N_matrix)] for m in range(N_matrix)])
D_2 = np.array([[-(h_bar*omega*alpha*1j)/4*np.sqrt(n)   * np.sqrt(n-1) if m==n-2 else 0 for n in range(N_matrix)] for m in range(N_matrix)])

In [142]:
D = D_0+D_1+D_2